### ISSUE TITLE
Using readRSRC on sub-vis without front panel

### ISSUE THREAD

**Issue by surrounded12** [mefistotelis/pylabview#4]
Hi, I'm trying to reverse engineer an executable, following your youtube tutorial. 
The first stage was well (extract a bunch of VIs,  add them to a project). I can open a couple of VIs that seem to have a front panel.
However, there are a few more that do not have a front panel and so cannot be opened. I tried following the tutorial and re-run readRSRC on them, but they ALL fail at exactly the same spot (which looks suspicious); 

# first there are 20-30 blocks recognized, then:
Test.vi: Block b'vers' max data size set to 56 bytes
Error: Block b'vers' section 4 always zero value 1 is 3 instead of 0
Traceback (most recent call last):
......

The project (exe) was made on Labview 2010.

Do you think this is a version issue, or something that can be addressed. It is strange that all (10-20 files) fail at the same spot (block b'vers').

disclaimer: I know very little about labVIEW!

Thanks

**Comment by mefistotelis** [comment]
Since in all the files I checked pylabview with, this value was 0, I couldn't implement it properly.

There's a comment in the code - in it, I speculate it's some kind of length, and may affect the following data.
Look into the code, check whether it is just a field which needs storing and re-creating or it's a length and a following field needs such storing. Then you can implement proper support of this.

**Comment by surrounded12** [comment]
I tried to mess around with it, but I don't know enough to make it work... So if anyone else decides to work on this, know that your effort is not reinventing the wheel!

**Comment by mefistotelis** [comment]
Fixed with:
https://github.com/mefistotelis/pylabview/commit/7b01960a1d66cec2ff583e4f876a16620c487b23
