### ISSUE TITLE
module 'pylabview' has no attribute 'LVdatatype'

### ISSUE THREAD

**Issue by Bars7878** [mefistotelis/pylabview#8]
Hi! 
After installing C:\Python36\Scripts>pip install pylabview
Collecting pylabview
  Using cached pylabview-0.1-py3-none-any.whl (224 kB)
Requirement already satisfied: Pillow in c:\python36\lib\site-packages (from pylabview) (8.4.0)
Installing collected packages: pylabview
Successfully installed pylabview-0.1

C:\pylabview-master\pylabview>python readRSRC.py
Traceback (most recent call last):
  File "readRSRC.py", line 25, in <module>
    from pylabview.LVrsrcontainer import *
  File "C:\Python36\lib\site-packages\pylabview\LVrsrcontainer.py", line 23, in <module>
    import pylabview.LVblock as LVblock
  File "C:\Python36\lib\site-packages\pylabview\LVblock.py", line 27, in <module>
    from pylabview.LVdatatype import *
  File "C:\Python36\lib\site-packages\pylabview\LVdatatype.py", line 25, in <module>
    import pylabview.LVclasses as LVclasses
  File "C:\Python36\lib\site-packages\pylabview\LVclasses.py", line 23, in <module>
    import pylabview.LVdatatype as LVrsrcontainer
AttributeError: module 'pylabview' has no attribute 'LVdatatype'

Please, help me resolve this error.

**Comment by mefistotelis** [comment]
Yeah, looks like @strainmike introduced a bug.

It was made in this commit:
https://github.com/mefistotelis/pylabview/commit/9b7ea5522afb9ceab87456a13e5c622e549a8c90

Feel free to provide a pull request with a fix.

**Comment by Bars7878** [comment]
I'm not sure I can figure it out quickly. But I need to use a script. Can you help?

**Comment by strainmike** [comment]
Do you get the same error if you run 
python -m pylabview.readRSRC
after pip installing it?

The import here definitely has a problem.  I'll post a PR to fix that: https://github.com/mefistotelis/pylabview/blob/92de71e41bdeb7d0ac06bce83fc0092b30500702/pylabview/LVclasses.py#L23

But it wouldn't cause the exact error you are getting.  I'm very confused by your error because LVdatatype is clearly on your system and accessible:
File "C:\Python36\lib\site-packages\pylabview\**LVdatatype**.py", line 25, in
import pylabview.LVclasses as LVclasses
File "C:\Python36\lib\site-packages\pylabview\LVclasses.py", line 23, in
import pylabview.LVdatatype as LVrsrcontainer
AttributeError: module 'pylabview' has no attribute 'LVdatatype'

**Comment by goldstar611** [comment]
> Successfully installed pylabview-0.1
> 
> C:\pylabview-master\pylabview>python readRSRC.py Traceback (most recent call last):

You are in a folder named pylabview. Change directories and see if the error happens

**Comment by mefistotelis** [comment]
Looks like besides a bug in switching to modules, this was also caused by support of Python 3.4 being untested and deteriorating over time.

Now with this commit, support of 3.4 is re-enabled:
https://github.com/mefistotelis/pylabview/commit/dc902ee74c347ea0177fa029025639093386d8e1

**Comment by mefistotelis** [comment]
...and the 3.4 support was dropped. Too many features from 3.5 were used.

Also, 3.5 support will be dropped in a few months, as Github will remove that from the actions (CI).

**Comment by goldstar611** [comment]
Hacking LabVIEW files is kind of a niche area so having a tool require a modern python version isn't a huge ask IMO. Pyinstaller can also be used in a pinch to bring a newer python over as needed. This approach has worked well for me in the past.

**Comment by ConyKitty** [comment]
The error is fixed, just note that the packagae on PyPI is not the latest (v0.1.2 now 2023.02.02), please use the source code rather than PyPI.
